data:extend({
  {
    type = "solar-panel",
    name = "number-one",
    icon = "__inftorio__/graphics/icons/number-one.png",
    icon_size = 32,
    icon_mipmaps = 4,
    flags = {"placeable-neutral", "player-creation"},
    minable = {hardness = 0.2, mining_time = 0.5, result = "number-one"},
    max_health = 100,
    corpse = "medium-remnants",
    collision_box = {{-0.5, -0.5}, {0.5, 0.5}},
    selection_box = {{-1.0, -1.0}, {1.0, 1.0}},
    energy_source =
    {
      type = "void",
      usage_priority = "primary-output"
    },
    picture =
    {
      filename = "__inftorio__/graphics/icons/number-one.png",
      priority = "high",
      width = 32,
      height = 32
    },
    production = "26000.67kW",
  },
  {
    type = "item",
    name = "number-one",
    icon = "__inftorio__/graphics/icons/number-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
    place_result = "number-one",
  },
  {
    type = "item",
    name = "number-two",
    icon = "__inftorio__/graphics/icons/number-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-three",
    icon = "__inftorio__/graphics/icons/number-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-four",
    icon = "__inftorio__/graphics/icons/number-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-five",
    icon = "__inftorio__/graphics/icons/number-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-six",
    icon = "__inftorio__/graphics/icons/number-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seven",
    icon = "__inftorio__/graphics/icons/number-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eight",
    icon = "__inftorio__/graphics/icons/number-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-nine",
    icon = "__inftorio__/graphics/icons/number-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ten",
    icon = "__inftorio__/graphics/icons/number-ten.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eleven",
    icon = "__inftorio__/graphics/icons/number-eleven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twelve",
    icon = "__inftorio__/graphics/icons/number-twelve.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirteen",
    icon = "__inftorio__/graphics/icons/number-thirteen.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fourteen",
    icon = "__inftorio__/graphics/icons/number-fourteen.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifteen",
    icon = "__inftorio__/graphics/icons/number-fifteen.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixteen",
    icon = "__inftorio__/graphics/icons/number-sixteen.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventeen",
    icon = "__inftorio__/graphics/icons/number-seventeen.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighteen",
    icon = "__inftorio__/graphics/icons/number-eighteen.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-nineteen",
    icon = "__inftorio__/graphics/icons/number-nineteen.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty",
    icon = "__inftorio__/graphics/icons/number-twenty.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-one",
    icon = "__inftorio__/graphics/icons/number-twenty-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-two",
    icon = "__inftorio__/graphics/icons/number-twenty-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-three",
    icon = "__inftorio__/graphics/icons/number-twenty-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-four",
    icon = "__inftorio__/graphics/icons/number-twenty-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-five",
    icon = "__inftorio__/graphics/icons/number-twenty-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-six",
    icon = "__inftorio__/graphics/icons/number-twenty-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-seven",
    icon = "__inftorio__/graphics/icons/number-twenty-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-eight",
    icon = "__inftorio__/graphics/icons/number-twenty-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-twenty-nine",
    icon = "__inftorio__/graphics/icons/number-twenty-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty",
    icon = "__inftorio__/graphics/icons/number-thirty.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-one",
    icon = "__inftorio__/graphics/icons/number-thirty-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-two",
    icon = "__inftorio__/graphics/icons/number-thirty-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-three",
    icon = "__inftorio__/graphics/icons/number-thirty-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-four",
    icon = "__inftorio__/graphics/icons/number-thirty-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-five",
    icon = "__inftorio__/graphics/icons/number-thirty-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-six",
    icon = "__inftorio__/graphics/icons/number-thirty-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-seven",
    icon = "__inftorio__/graphics/icons/number-thirty-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-eight",
    icon = "__inftorio__/graphics/icons/number-thirty-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-thirty-nine",
    icon = "__inftorio__/graphics/icons/number-thirty-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty",
    icon = "__inftorio__/graphics/icons/number-forty.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-one",
    icon = "__inftorio__/graphics/icons/number-forty-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-two",
    icon = "__inftorio__/graphics/icons/number-forty-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-three",
    icon = "__inftorio__/graphics/icons/number-forty-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-four",
    icon = "__inftorio__/graphics/icons/number-forty-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-five",
    icon = "__inftorio__/graphics/icons/number-forty-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-six",
    icon = "__inftorio__/graphics/icons/number-forty-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-seven",
    icon = "__inftorio__/graphics/icons/number-forty-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-eight",
    icon = "__inftorio__/graphics/icons/number-forty-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-forty-nine",
    icon = "__inftorio__/graphics/icons/number-forty-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty",
    icon = "__inftorio__/graphics/icons/number-fifty.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-one",
    icon = "__inftorio__/graphics/icons/number-fifty-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-two",
    icon = "__inftorio__/graphics/icons/number-fifty-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-three",
    icon = "__inftorio__/graphics/icons/number-fifty-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-four",
    icon = "__inftorio__/graphics/icons/number-fifty-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-five",
    icon = "__inftorio__/graphics/icons/number-fifty-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-six",
    icon = "__inftorio__/graphics/icons/number-fifty-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-seven",
    icon = "__inftorio__/graphics/icons/number-fifty-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-eight",
    icon = "__inftorio__/graphics/icons/number-fifty-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-fifty-nine",
    icon = "__inftorio__/graphics/icons/number-fifty-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty",
    icon = "__inftorio__/graphics/icons/number-sixty.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-one",
    icon = "__inftorio__/graphics/icons/number-sixty-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-two",
    icon = "__inftorio__/graphics/icons/number-sixty-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-three",
    icon = "__inftorio__/graphics/icons/number-sixty-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-four",
    icon = "__inftorio__/graphics/icons/number-sixty-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-five",
    icon = "__inftorio__/graphics/icons/number-sixty-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-six",
    icon = "__inftorio__/graphics/icons/number-sixty-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-seven",
    icon = "__inftorio__/graphics/icons/number-sixty-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-eight",
    icon = "__inftorio__/graphics/icons/number-sixty-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-sixty-nine",
    icon = "__inftorio__/graphics/icons/number-sixty-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy",
    icon = "__inftorio__/graphics/icons/number-seventy.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-one",
    icon = "__inftorio__/graphics/icons/number-seventy-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-two",
    icon = "__inftorio__/graphics/icons/number-seventy-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-three",
    icon = "__inftorio__/graphics/icons/number-seventy-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-four",
    icon = "__inftorio__/graphics/icons/number-seventy-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-five",
    icon = "__inftorio__/graphics/icons/number-seventy-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-six",
    icon = "__inftorio__/graphics/icons/number-seventy-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-seven",
    icon = "__inftorio__/graphics/icons/number-seventy-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-eight",
    icon = "__inftorio__/graphics/icons/number-seventy-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-seventy-nine",
    icon = "__inftorio__/graphics/icons/number-seventy-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty",
    icon = "__inftorio__/graphics/icons/number-eighty.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-one",
    icon = "__inftorio__/graphics/icons/number-eighty-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-two",
    icon = "__inftorio__/graphics/icons/number-eighty-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-three",
    icon = "__inftorio__/graphics/icons/number-eighty-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-four",
    icon = "__inftorio__/graphics/icons/number-eighty-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-five",
    icon = "__inftorio__/graphics/icons/number-eighty-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-six",
    icon = "__inftorio__/graphics/icons/number-eighty-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-seven",
    icon = "__inftorio__/graphics/icons/number-eighty-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-eight",
    icon = "__inftorio__/graphics/icons/number-eighty-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-eighty-nine",
    icon = "__inftorio__/graphics/icons/number-eighty-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety",
    icon = "__inftorio__/graphics/icons/number-ninety.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-one",
    icon = "__inftorio__/graphics/icons/number-ninety-one.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-two",
    icon = "__inftorio__/graphics/icons/number-ninety-two.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-three",
    icon = "__inftorio__/graphics/icons/number-ninety-three.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-four",
    icon = "__inftorio__/graphics/icons/number-ninety-four.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-five",
    icon = "__inftorio__/graphics/icons/number-ninety-five.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-six",
    icon = "__inftorio__/graphics/icons/number-ninety-six.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-seven",
    icon = "__inftorio__/graphics/icons/number-ninety-seven.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-eight",
    icon = "__inftorio__/graphics/icons/number-ninety-eight.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
  {
    type = "item",
    name = "number-ninety-nine",
    icon = "__inftorio__/graphics/icons/number-ninety-nine.png",
   	order = "a-a-a",
    stack_size = 500,
    icon_size = 32,
  },
})